version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        patterns: ['ruff', 'mypy', 'pytest*', 'fakeredis', 'django-stubs*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
